apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - networkpolicy.yaml
  - serviceaccount.yaml
  - openbao-agent-config.yaml
  - certificate.yaml
  - service.yaml
  - statefulset.yaml
  - servicemonitor.yaml
