apiVersion: v1
kind: Service
metadata:
  name: release-feed
  namespace: release-feed
  labels:
    app.kubernetes.io/name: release-feed
    shell.platform/owner: make
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: release-feed
  ports:
    - name: https
      port: 443
      nodePort: 30444
      targetPort: https
      protocol: TCP
