apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-server-tls
  namespace: openbao
  labels:
    app.kubernetes.io/name: openbao
spec:
  secretName: openbao-server-tls
  duration: 2160h
  renewBefore: 720h
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
  usages:
    - server auth
    - client auth
    - digital signature
    - key encipherment
  dnsNames:
    - openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-active
    - openbao-active.openbao.svc
    - openbao-active.openbao.svc.cluster.local
    - openbao-standby
    - openbao-standby.openbao.svc
    - openbao-standby.openbao.svc.cluster.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: shell-cluster-intermediate
