---
# yamllint disable rule:line-length
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tempo-default-deny
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: tempo
      app.kubernetes.io/instance: tempo
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: shell-otel
      ports:
        - {port: 4317, protocol: TCP}
        - {port: 4318, protocol: TCP}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - {port: 3200, protocol: TCP}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - {port: 53, protocol: UDP}
        - {port: 53, protocol: TCP}
# yamllint enable rule:line-length
