---
# yamllint disable rule:line-length
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shell-kyverno
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: shell-platform
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: shell-platform-services
  sources:
    - repoURL: registry.shell.internal/shell/charts
      chart: kyverno
      targetRevision: 3.8.2
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/gitops/values/kyverno.yaml
    - repoURL: https://forgejo.shell.internal/shell/make.git
      targetRevision: main
      ref: values
    - repoURL: https://forgejo.shell.internal/shell/make.git
      targetRevision: main
      path: gitops/platform/kyverno
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
# yamllint enable rule:line-length
