---
# yamllint disable rule:line-length
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: watch-tempo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: shell-platform
  annotations:
    argocd.argoproj.io/sync-wave: "50"
spec:
  project: shell-platform-services
  sources:
    - repoURL: registry.shell.internal/shell/charts
      chart: tempo
      targetRevision: 1.24.4
      helm:
        releaseName: tempo
        valueFiles:
          - $values/gitops/values/tempo.yaml
    - repoURL: https://forgejo.shell.internal/shell/make.git
      targetRevision: main
      ref: values
    - repoURL: https://forgejo.shell.internal/shell/make.git
      targetRevision: main
      path: gitops/platform/tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
# yamllint enable rule:line-length
